<?php /* @var $this Ebizmarts_SagePayReporting_Block_Adminhtml_Sagepayreporting_Switcher */ ?>
<div class="switcher">
    <label for="store_switcher"><?php echo $this->__('Current Configuration Scope:') ?></label>
    <select id="store_switcher" class="system-config-store-switcher" onchange="location.href=this.options[this.selectedIndex].getAttribute('url')">
    <?php foreach ($this->getStoreSelectOptions() as $_value => $_option): ?>
    <?php if (isset($_option['is_group'])): ?>
        <?php if ($_option['is_close']): ?>
            </optgroup>
        <?php else: ?>
            <optgroup label="<?php echo $this->escapeHtml($_option['label']) ?>" style="<?php echo $_option['style'] ?>">
        <?php endif; ?>
        <?php continue ?>
    <?php endif; ?>
      <option value="<?php echo $this->escapeHtml($_value) ?>" url="<?php echo $_option['url'] ?>" <?php echo $_option['selected'] ? 'selected="selected"' : '' ?> style="<?php echo $_option['style'] ?>">
          <?php echo $this->escapeHtml($_option['label']) ?>
      </option>
    <?php endforeach ?>
    </select>
</div>