<?php
	$_code = $this->getMethodCode();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<?php
		foreach($this->getTokenCards($_code) as $_tcard):
		$radioId = $_code . '_tokencard_' . $_tcard->getId();
	?>
		<li>
			<input type="radio" id="<?php echo $radioId; ?>" name="payment[cc_id]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-radio" value="<?php echo $_tcard->getId(); ?>" /><label for="<?php echo $radioId; ?>"><?php echo $_tcard->getCcNumber(); ?></label>
		</li>
	<?php endforeach; ?>
</ul>