<?php
	$c          = $this->getPaymentMethodCode();
	$tokenCards = $this->getAvailableTokenCards($c);
	$cTokens    = ($tokenCards->getSize()>0 && $this->getCanUseToken());
    if($cTokens > 0):
    	$defToken = $this->helper('sagepaysuite/token')->getDefaultToken();
    ?>
    <div id="tokencards-payment-<?php echo $c; ?>"<?php if($c == 'sagepayserver'): ?> class="nothide"<?php endif; ?>>
    <ul class="form-list tokensage">
    <?php
        $default_token = "";
    	foreach($tokenCards as $_tcard):
		$radioId = $c . '_tokencard_' . $_tcard->getId();
		$isDef = $_tcard->getId() == $defToken->getId();
	?>
		<li class="tokencard-radio">
			<input<?php if($isDef): ?> checked="checked"<?php endif; ?> type="radio" id="<?php echo $radioId; ?>" name="payment[sagepay_token_cc_id]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-radio" value="<?php echo $_tcard->getId(); ?>" onclick="switchToken(this,'<?php echo $_tcard->getCardType(); ?>');" />
            <label class="token" for="<?php echo $radioId; ?>"><?php echo $this->__('%s, Exp. %s', $_tcard->getCcNumber(), $_tcard->getExpireDate()); ?> <?php if($_tcard->Nickname !== NULL){ echo ' - '.$_tcard->Nickname; } ?></label>
			<img width="35" src="<?php echo $this->helper('sagepaysuite')->getCcImage($this->helper('sagepaysuite')->getCardLabel($_tcard->getCardType(), false)); ?>" />&nbsp;&nbsp;&nbsp;

			<?php if($c != 'sagepayserver'): ?>
			<div class="tokencvv"<?php if(!$isDef): ?> style="display:none"<?php endif; ?>>
		        <label class="required" for="<?php echo $c ?>_token_cvv_<?php echo $_tcard->getId(); ?>"><em>*</em><?php echo $this->__('CV2'); ?></label>
		        <input<?php if(!$isDef){ echo " disabled"; } ?> type="text" id="<?php echo $c ?>_token_cvv_<?php echo $_tcard->getId(); ?>" name="payment[token_cvv]" title="<?php echo $this->__('Credit Card CV2') ?>" class="input-text required-entry validate-digits cvv tokencvv" onfocus="tokenRadioCheck('<?php echo $radioId; ?>', this);" />
	        </div>
	        <?php endif; ?>

		<a class="oncheckout" href="<?php echo $this->getUrl('sgps/card/delete/', array('card'=>$_tcard->getId(), '_secure' => true)); ?>" onclick="if(confirm('<?php echo $this->__("Are you sure?"); ?>')){removeCard(this); return false; }else{return false;}"><?php echo $this->__('Delete'); ?></a>
		</li>
            <?php ;
            if($isDef) {
                $default_token = $_tcard->getCardType();
            }
            ?>
	<?php endforeach; ?>
	</ul>
    <input type="hidden" id="<?php echo $c ?>_cc_type_token" name="payment[cc_type_token]" value="<?php echo $default_token; ?>" />
	</div>
	<a class="addnew" href="" onclick="toggleNewCard(2); return false;"><?php echo $this->__('Add new'); ?></a>
<?php else: ?>
    <div id="tokencards-payment-<?php echo $c; ?>">&nbsp;</div>
	<a style="display:none;" class="addnew" href="" onclick="toggleNewCard(2); return false;"><?php echo $this->__('Add new'); ?></a>
<?php endif; ?>