<?php
	$_code = $this->getMethodCode();
	$sageStyle = '';
    $_directMode = Mage::getStoreConfig('payment/sagepaydirectpro_moto/mode');
?>
<script type="text/javascript">
    var RDATE = <?php echo rand(1,10); ?>;
</script>
<div  id="payment_form_<?php echo $_code ?>" style="display:none;">

<?php echo $this->getChildHtml(); ?>

<ul class="form-list">
    <li>
        <label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?> <span class="required">*</span></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" onchange="changecsvclass(this);" class="required-entry validate-ccsgpdp-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label>
        <div class="input-box">
            <input autocomplete="off" type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-ccsgpdp-number validate-ccsgpdp-type" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label>
        <br />
        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
        <?php endforeach ?>
        </select>
        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
        <?php foreach ($this->getCcYears() as $k=>$v): ?>
            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
        <?php endforeach ?>
        </select>
    </li>
    <?php #if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label>
        <div class="input-box">
            <div class="v-fix">
                <input autocomplete="off" type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv validate-ccsgpdp-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
        </div>
    </li>
    <?php #endif; ?>

	<?php if ($this->allowGiftAid()): ?>
    <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_giftaid_div">
        <label for="<?php echo $_code ?>_cc_giftaid"><?php echo $this->__('Donate Taxes') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="checkbox" title="<?php echo $this->__('Donate Taxes') ?>" class="input-text checkbox" id="<?php echo $_code ?>_cc_giftaid" name="payment[cc_giftaid]" />
            </div>
        </div>
    </li>
    <?php endif; ?>

    <?php if ($this->hasSsCardType()): ?>
    <li id="<?php echo $_code ?>_cc_type_ss_div">
    <ul class="inner-form">
        <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Switch/Solo Only') ?> <span class="required">*</span></label></li>
        <li>
            <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                    <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
            </div></div>
        </li>

        <li>
            <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
            <br />
                    <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                    <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                    <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
        </li>

        <li class="adv-container">&nbsp;</li>
   </ul>
    <script type="text/javascript">
	var SSChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');

			if(elm.value=='' || ($$('ul#payment_form_sagepaydirectpro li.tokencard-radio input[type="radio"]:enabled').length > 0)){
        		return;
        	}
            if (['SOLO','SWITCH'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_ss_div').show();
            } else {
                $('<?php echo $_code ?>_cc_type_ss_div').hide();
            }
    };

    Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
    SSChecked<?php echo $_code ?>();
    </script>
</li>
<?php endif; ?>
</ul>
</div>