<?php $_code = 'sagepaytoken'; ?>
</br>
<label for="<?php echo $_code ?>_cc_nickname"><?php echo $this->__('Credit Card Description') ?></label>
<div class="input-box">
    <input type="text" title="<?php echo $this->__('Credit Card Description') ?>" class="input-text" id="<?php echo $_code ?>_cc_nickname" name="Nickname" />
</div>
</br>
<iframe src="<?php echo $this->getNextUrl(); ?>" id="iframeRegCard"></iframe>
