<?php

    $canShow = (bool)Mage::getStoreConfigFlag('payment/sagepaysuite/orphans_notification') && Mage::getSingleton('admin/session')->isAllowed('sales/sagepay/orphans');

    if(true === $canShow):

    $goOrphan = $this->helper('sagepaysuite')->__('Click here to go to <a href="%s">Orphan Transactions List</a>.', $this->helper('adminhtml')->getUrl('adminhtml/spsTransaction/orphan'));
    $whatsThis = $this->helper('sagepaysuite')->__('<a target="_blank" href="%s">What\'s this?</a>', 'http://ebizmarts.com/blog/2013/07/sage-pay-orphan-transactions');
    $_orphans = $this->helper('sagepaysuite')->orphanTransactionsFlag();
?>
<?php if($_orphans):?>
<div class="notification-global">
    <img style="vertical-align: middle;" src="<?php echo $this->getSkinUrl('sagepaysuite/images/sagepay-section.png'); ?>" />&nbsp;<strong><?php echo $this->helper('sagepaysuite')->__('One or more transactions have no order associated.') ?></strong>
    <?php echo $goOrphan;?>  <?php echo $whatsThis;?>
</div>
<?php endif;?>

<?php endif;//$canShow ?>
